--[[  Generated by FAF Map Editor                                              ]]--
-- Table of which resources belong to which player, it is sorted in such a way that the first line
-- corresponds to player one, the second to player 2 and so on...

maxPlayerOnMap = 16




-- Line number is 10 + armynumber for the mexes in the table
spwnMexArmy = {		{29,30,31},
                    {08,10,11},
                    {123,125,127},
                    {129,131,133},
                    {32,33,34},
                    {04,05,07},
                    {24,25,27},
                    {12,13,15},
                    {101,102,99},
                    {107,108,109},
                    {113,114,115},
                    {119,120,121},
                    {36,38,39},
                    {01,02,03},
                    {20,22,23},
                    {17,18,19}}



-- Line number is 30 + armynumber for the hydros in the table
spwnHydroArmy = {	{07},
                    {02},
                    {14},
                    {15},
                    {10},
                    {05},
                    {09},
                    {06},
                    {00},
                    {01},
                    {12},
                    {13},
                    {11},
                    {03},
                    {08},
                    {04}}


-- RESOURCE SCALING OPTIONS
-- exampleMexes = {{1,2},{3,4},{5,6}},        -- exampleMexes = {{1,2}}
-- exampleMexes = {{a},{b},{c}},              -- exampleMexes = {{a}}
-- option key=1 : removes a+b+c               -- option key=1 : removes a
-- option key=2 : spawn a, removes b+c        -- option key=2 : spawns a
-- option key=3 : spawn a+b, removes c
-- option key=4 : spawn a+b+c

extraHydros = {{}}

extraMexes = {{}}

middleMexes = {{},{},{}}

sideMexes = {{},{},{}}

underwaterMexes = {{},{},{}}

islandMexes = {{},{},{}}

expansionMexes = {{},{},{}}

coreMexes = {{}}

extraBaseMexes = {{}}

topSideMexes = {{},{},{}}

bottomSideMexes = {{},{},{}}

forwardCrazyrushMexes = {}

crazyrushOneMexes = {}

