--[[  Generated by FAF Map Editor                                              ]]--
-- Table of which resources belong to which player, it is sorted in such a way that the first line
-- corresponds to player one, the second to player 2 and so on...

maxPlayerOnMap = 10




-- Line number is 10 + armynumber for the mexes in the table
spwnMexArmy = {		{00,02,04,60},
                    {01,03,05,59},
                    {06,08,10,31,64},
                    {07,09,11,32,63},
                    {12,14,16,66},
                    {13,15,17,65},
                    {31,53,55,57,62},
                    {32,54,56,58,61},
                    {41,49,51,68},
                    {42,50,52,67},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {}}



-- Line number is 30 + armynumber for the hydros in the table
spwnHydroArmy = {	{00},
                    {01},
                    {02},
                    {03},
                    {04},
                    {05},
                    {08},
                    {09},
                    {06},
                    {07},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {}}


-- RESOURCE SCALING OPTIONS
-- exampleMexes = {{1,2},{3,4},{5,6}},        -- exampleMexes = {{1,2}}
-- exampleMexes = {{a},{b},{c}},              -- exampleMexes = {{a}}
-- option key=1 : removes a+b+c               -- option key=1 : removes a
-- option key=2 : spawn a, removes b+c        -- option key=2 : spawns a
-- option key=3 : spawn a+b, removes c
-- option key=4 : spawn a+b+c

extraHydros = {{10,11}}

extraMexes = {{}}

middleMexes = {{18,20,22},{19,21,23,24},{25,26,27,28}}

sideMexes = {{},{},{}}

underwaterMexes = {{},{},{}}

islandMexes = {{},{},{}}

expansionMexes = {{},{},{}}

coreMexes = {{}}

extraBaseMexes = {{04,05,06,07,12,13,55,56,67,68}}

topSideMexes = {{},{},{}}

bottomSideMexes = {{},{},{}}

forwardCrazyrushMexes = {}

crazyrushOneMexes = {}

